### ISSUE TITLE
Cryptpad with Docker and Nginx - Pads Won't Load (Connection Reset Error)

### ISSUE THREAD

**Issue by novams** [xwiki-labs/cryptpad#216]
This issue originally involved Traefik but I abandoned that plan as I wasn't making any progress with it. However, it seems even with Nginx the problem persists. The write up below has been edited to reflect the current state of the problem.

I'm attempting to set up Cryptpad via Docker, reachable through an Nginx container, on a public server. I can can currently access the app over HTTPS and browse all the main, standard pages of the application (e.g. index.html, what-is-cryptpad.html, about.html, login.html, etc.). I can even register a user. However, upon trying to navigate to any of the 'pads', I get a connection reset error in the browser. Similarly, if I register a user I get redirected to /drive, which results in a connection reset error as well.

This is my current `docker-compose.yml` file for Cryptpad:

```
version: '2'
services:

  cryptpad:
    build:
      context: .
      args:
        - VERSION=${VERSION}
    image: "xwiki/cryptpad:${VERSION}"
    hostname: cryptpad

    environment:
      - USE_SSL=${USE_SSL}
      - STORAGE=${STORAGE}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT}
    restart: always
    volumes:
      - ./data/files:/cryptpad/datastore:rw
      - ./data/customize:/cryptpad/customize:rw
    networks:
      - proxy
    expose:
      - "3000"

networks:
  proxy:
    external:
      name: proxy
```

and this is my `docker-compose.yml` file for Nginx:

```
version: '3'

services:

  nginx-proxy:
    image: "nginx:latest"  
    container_name: nginx-proxy
    restart: always
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./www:/var/www/
    networks:
      - proxy 

networks:
  proxy:
    external:
      name: proxy
```

Further, this is my current nginx configuration file:

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

upstream docker-cryptpad {
        server cryptpad:3000;
}


server {
    listen 80;
    
    server_name cryptpad.myserver.com

    return 301 https://cryptpad.myserver.com$request_uri;

}

server {
    listen 443 ssl;

    server_name cryptpad.myserver.com www.cryptpad.myserver.com;

    ssl_certificate         /etc/letsencrypt/live/cryptpad.myserver.com-0001/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/cryptpad.myserver.com-0001/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    
    location / {
        proxy_redirect off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        
        proxy_pass http://docker-cryptpad;
    }

    location = /cryptpad_websocket {
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        proxy_pass http://docker-cryptpad/cryptpad_websocket;
    }
  
}
```

And finally, these logs don't show much but here are the nginx logs:

```
5.144.202.89 - - [14/Jan/2018:20:19:49 +0000] "GET /pad/ HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
5.144.202.89 - - [14/Jan/2018:20:19:50 +0000] "GET /api/config?cb=160f65405d6 HTTP/1.1" 200 391 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
5.144.202.89 - - [14/Jan/2018:20:19:50 +0000] "GET /bower_components/jquery/dist/jquery.min.map HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"

```
I won't include the data/customize/config.js file here as I haven't changed anything in it. So in other words it still looks like this: https://github.com/xwiki-labs/cryptpad/blob/master/config.example.js.

Any help would be greatly appreciated, as I have pretty much reached my limit of ideas on how to solve this. Of course, I can provide more details if necessary. Thank you!
