### ISSUE TITLE
Presentation custom css is not allowed to reference external fonts

### ISSUE THREAD

**Issue by grinapo** [xwiki-labs/cryptpad#760]
**Describe the bug**
Editing Presentation custom CSS seems have (security-related) limits:

 Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css2?family=Newsreader&display=swap (“connect-src”). 2 less.min.js:13:7721
 Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css2?family=Newsreader&display=swap (“font-src”). 2 jquery.min.js:3:18201
 Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css2?family=Newsreader&display=swap (“font-src”).

**Expected behavior**
To redefine the fonts in the presentation `font-src` shall be at least usable.

**Browser (please complete the following information):**
 - OS: debian
 - Browser : firefox
   - variations : nightly
 - Version : latest
 - Extensions installed: aplenty, but probably not relevant

**Additional info**
Custom CSS example would be neat. That's what I have tried:
```css
@font-face {
 font-family: Newsreader;
 src: url('https://fonts.googleapis.com/css2?family=Newsreader&display=swap');
}

.cp-app-slide {
 font-family: Newsreader;
}
```
