### ISSUE TITLE
Dockerhub repository 404ing

### ISSUE THREAD

**Issue by dewey** [xwiki-labs/cryptpad#84]
Looks like the image is not on docker hub any more:

https://www.docker.com/xwiki/cryptpad

**Comment by ansuz** [comment]
Hi,

everything docker-related was added in a PR. We don't actually use docker for our deployments, so I'm not sure how to go about addressing this issue.

**Comment by ansuz** [comment]
@felixboehm, can you comment on how this should be working?

**Comment by felixboehm** [comment]
docker hub is here https://hub.docker.com
sou can find images there, but the image described by the dockerfile in this repo is not pushed to the hub. you can do so if you want ...

**Comment by dewey** [comment]
Right, I pushed a new image to my docker repo and with that config it's working now. Kinda, I still have a problem that it's stuck at the "Loading" screen after clicking on "New Code Pad" but that's another issue I guess...

```
version: '2'
services:
  cryptpad:
    image: "tehwey/docker-cryptpad:latest"
    hostname: cryptpad
    ports:
      - "3010:3000"
    environment:
      - USE_SSL=false
      - STORAGE='./storage/file'
      - LOG_TO_STDOUT=true

    restart: always
    volumes:
      - ./data/files:/cryptpad/datastore:rw
      - ./data/customize:/cryptpad/customize:rw
```
