### ISSUE TITLE
CSP `connect-src` rewriten by the application?

### ISSUE THREAD

**Issue by jonatasbaldin** [xwiki-labs/cryptpad#924]
**Describe the bug**
I'm running https://github.com/xwiki-labs/cryptpad-docker/ with a Caddy reverse proxy in front of it for TLS termination.

For some reason, the `connect-src` directive of the CSP is being _rewritten_ (?) by Cryptpad. Instead of the `wss://` I only receive `https://` scheme.

If I access the application directly from within the container and run curl, this is what I get:

```
$ curl -I http://localhost:3000 --insecure

...
Content-Security-Policy: [...] connect-src 'self' blob: https://cryptpad.uncloud.do https://cryptpad.uncloud.do https://sandbox.cryptpad.uncloud.do [...]
...
```

The `connect-src` has only `https` schemes (but not `wss`). 

The NGINX in front of it configures the correct `connect-src`, but I still receive the _only_ `https scheme` answer.

Is this a bug? Any clues?

**To Reproduce**
Create a `docker-compose.yaml` file:
```
services:
  cryptpad:
    image: promasu/cryptpad:v5.0.0-nginx-alpine
    restart: unless-stopped
    networks:
      - reverse-proxy
      - default
    volumes:
      - {{ apps_path }}/cryptpad//config.js:/cryptpad/config/config.js
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore

    environment:
      CPAD_MAIN_DOMAIN: "cryptpad.{{ domain }}"
      CPAD_SANDBOX_DOMAIN: "sandbox.cryptpad.{{ domain }}"

    # specific for my proxy, not _required_
    labels:
      caddy: "cryptpad.{{ domain }}, sandbox.cryptpad.{{ domain }}"
      caddy.reverse_proxy.header_down_0: "cross-origin-embedder-policy require-corp"
      caddy.reverse_proxy.header_down_1: "cross-origin-resource-policy cross-origin"
      caddy.reverse_proxy: {% raw %} "{{upstreams 3000}}" {% endraw %}

volumes:
  data:

networks:
  reverse-proxy:
    external: true
```

Try to `curl` from within the container:
```
$ docker-compose exec cryptpad sh
$ /cryptpad # apk add curl
$ /cryptpad # curl -I localhost:3000 

Content-Security-Policy: [...] connect-src 'self' blob: https://cryptpad.uncloud.do https://cryptpad.uncloud.do https://sandbox.cryptpad.uncloud.do [...]
```

I can't `curl` directly to NGINX from within the container, I get:
```
$ curl -I http://localhost
curl: (1) Received HTTP/0.9 when not allowed
```

From my Caddy proxy, I can curl and receive the same response:
```
$ curl -I https://cryptpad.local/ --insecure        
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: https://sandbox.cryptpad.local
cache-control: no-cache
content-security-policy: default-src 'none'; style-src 'unsafe-inline' 'self' https://cryptpad.local; font-src 'self' data: https://cryptpad.local; child-src https://cryptpad.local; frame-src 'self' blob: https://sandbox.cryptpad.local; connect-src 'self' blob: https://cryptpad.local https://cryptpad.local https://sandbox.cryptpad.local; img-src 'self' data: blob: https://cryptpad.local; media-src blob:; frame-ancestors 'self' https://cryptpad.local; worker-src 'self'; script-src 'self' resource: https://cryptpad.local
content-type: text/html; charset=UTF-8
cross-origin-resource-policy: cross-origin
date: Tue, 21 Jun 2022 09:24:56 GMT
etag: W/"402-18159ef5ca0"
last-modified: Sun, 12 Jun 2022 22:01:08 GMT
permissions-policy: interest-cohort=()
server: Caddy
x-content-type-options: nosniff
x-powered-by: Express
x-xss-protection: 1; mode=block
content-length: 1026
```

**Expected behavior**
Even with NGINX properly configured (by default), the CSP header returned seems to be rewritten somewhere. I don't `Caddy` is responsible for this, since the Cryptpad returns the same header.

**Browser (please complete the following information):**
- OSX
- `curl`
